name: Build and Deploy to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to Hostinger via Git
        uses: actions/checkout@v4
        with:
          ref: ${{ github.sha }}
          path: build-temp

      - name: Copy build files to repository root
        run: |
          cp -r build/* build-temp/
          cd build-temp
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy build files - ${{ github.sha }}"
          git push origin main

      - name: Trigger Hostinger deployment
        run: |
          # This step will trigger Hostinger's webhook if configured
          echo "Build completed and pushed to main branch"
          echo "Hostinger should automatically deploy from the updated main branch"
